FROM arm64v8/python:3.11-slim

# Install build dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /work

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install pyinstaller && \
    pip install -r requirements.txt